name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
              
      - name: Build and push Docker image
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login --username AWS -p ${{ secrets.ECR_REGISTRY }}
          docker buildx build --platform linux/amd64 -t ${{ secrets.ECR_REGISTRY }}/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) 101464699422.dkr.ecr.eu-central-1.amazonaws.com

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment --region $AWS_REGION
