name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Configure AWS Creds
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}; aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Build and push Docker image
        env:
          ECR_REPOSITORY: 101464699422.dkr.ecr.eu-central-1.amazonaws.com/softcery-repository
          AWS_REGION: eu-central-1
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login -u AWS -p $(aws ecr get-login-password --region eu-central-1) 101464699422.dkr.ecr.eu-central-1.amazonaws.com/softcery-repository
          docker build -t 101464699422.dkr.ecr.eu-central-1.amazonaws.com/softcery-repository:$IMAGE_TAG .
          docker push 101464699422.dkr.ecr.eu-central-1.amazonaws.com/softcery-repository:$IMAGE_TAG

      - name: Update ECS service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          ECS_CLUSTER_NAME: softcery-cluster
          ECS_SERVICE_NAME: softcery-service
          ECR_REPOSITORY: 101464699422.dkr.ecr.eu-central-1.amazonaws.com/softcery-repository
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment --region $AWS_REGION
