name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
              
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: $ECR_REPOSITORY
          AWS_REGION: $AWS_REGION
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | aws ecr --region $AWS_REGION | docker login -u AWS -p $ECR_REPOSITORY
          docker buildx build --platform linux/amd64 -t ${{ secrets.ECR_REGISTRY }}/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update ECS service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: $AWS_REGION
          ECS_CLUSTER_NAME: $ECS_CLUSTER_NAME
          ECS_SERVICE_NAME: $ECS_SERVICE_NAME
          ECR_REPOSITORY: $ECR_REPOSITORY
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment --region $AWS_REGION
